import type { Metadata } from 'next';
import { config as CONFIG } from '@/config';

export const metadata: Metadata = {
    title: CONFIG.appName,
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
    params: { locale },
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    // Get  messages and provide to client

    return (
        <html lang={locale}>
            <body>{children}</body>
        </html>
    );
}
