import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { getMessages, unstable_setRequestLocale } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
import { config as CONFIG } from '@/config';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: CONFIG.appName,
    description: 'Generated by create next app',
};

export function generateStaticParams() {
    return CONFIG.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
    children,
    params: { locale },
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    // Enable static rendering
    unstable_setRequestLocale(locale);
    // Get  messages and provide to client
    const messages = await getMessages();

    return (
        <html lang={locale}>
            <body className={inter.className}>
                <NextIntlClientProvider messages={messages}>
                    {children}
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
